# Generated by Django 4.0.6 on 2022-07-24 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0002_alter_user_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk', models.CharField(max_length=256)),
                ('space', models.ForeignKey(db_column='space_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='config.space')),
            ],
            options={
                'db_table': 'chat',
            },
        ),
    ]
