# Generated by Django 4.0.6 on 2022-07-24 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'space',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=128, unique=True)),
                ('nickname', models.CharField(max_length=128)),
                ('space', models.ForeignKey(db_column='space_id', on_delete=django.db.models.deletion.CASCADE, to='config.space')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
