# Generated by Django 4.0.6 on 2022-07-24 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='space',
            field=models.ForeignKey(db_column='space_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='config.space'),
        ),
    ]
